training_pipeline_config:
  pipeline_name: concrete_src
  artifact_dir: artifact

data_ingestion_config:
  dataset_name: elikplim/concrete-compressive-strength-data-set
  dataset_file_name: concrete_data.csv
  raw_data_dir: raw_data
  ingested_dir: ingested_data
  ingested_train_dir: train

data_validation_config:
  schema_dir: config
  schema_file_name: schema.yaml

data_transformation_config:
  transformed_dir: transformed_data
  transformed_train_dir: train
  preprocessing_dir: preprocessed
  preprocessed_object_file_name: preprocessed.pkl

model_trainer_config:
  trained_model_dir: trained_model
  model_file_name: model
  base_accuracy: 0.25
  model_config_dir : "config"
  model_config_file_name : "model.yaml"

model_evaluation_config:
  model_evaluation_file_prefix: model_evaluation_cluster_

model_pusher_config:
  model_export_dir: saved_models