training_pipeline_config:
  pipeline_name: concrete_src
  artifact_dir: artifact

data_ingestion_config:
  dataset_name: elikplim/concrete-compressive-strength-data-set
  dataset_file_name: concrete_data.csv
  raw_data_dir: raw_data

data_validation_config:
  schema_dir: config
  schema_file_name: schema.yaml