grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 5
    verbose: 2
models:
  model_0:
    class: Ridge
    module: sklearn.linear_model
    params:
      fit_intercept: true
      alpha: 1.0
    search_param_grid:
      fit_intercept:
      - true
      - false
  model_1:
    class: GradientBoostingRegressor
    module: sklearn.ensemble
    params:
      min_samples_leaf: 3
      learning_rate: 0.1
      max_depth: 2
      max_features: None
      max_leaf_nodes: 2
      n_estimators: 100
      subsample: 0.8
    search_param_grid:
      min_samples_leaf:
      - 3
      - 6
      max_depth:
      - 3
      - 4
      max_features:
      - sqrt
      - None
      max_leaf_nodes:
      - 2
      - 4
      n_estimators:
      - 200
      subsample:
      - 0.8
  model_2:
    class: SVR
    module: sklearn.svm
    params:
      C: 10
      gamma: 0.1
      kernal: rbf
      epsilon: 0.1
    search_param_grid:
      C:
      - 0.1
      - 10
      - 1000
      gamma:
      - 0.1
      - 1
      - .01
      - .001
  model_3:
    class: KNeighborsRegressor
    module: sklearn.neighbors
    params:
      n_neighbors: 5
      weights: distance
      kernal: rbf
      leaf_size: 25
    search_param_grid:
      n_neighbors:
      - 7
      - 10
      - 20
      weights:
      - distance
      leaf_size:
      - 20
      - 10
  model_4:
    class: RandomForestRegressor
    module: sklearn.ensemble
    params:
      min_samples_split: 2
      max_features: auto
      n_estimators: 100
      bootstrap: True
    search_param_grid:
      min_samples_split:
      - 2
      - 4
      - 8
      max_features:
      - sqrt
      - auto
      - log2
      n_estimators:
      - 200
      bootstrap:
      - true
      - false
